Use {database};

DROP TABLE IF EXISTS {Tablename};

CREATE TABLE Account_1(
	ID INT PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	TRANS_AMT FLOAT,
	TRANS_TYPE VARCHAR (50),
	LOCATION VARCHAR (100) NOT NULL
);
