Use database;

DROP TABLE IF EXISTS {Tablename};

CREATE TABLE Account_1(
	ID INT PRIMARY KEY,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	TRANS_AMT (),
	TRANS_TYPE(),
	LOCATION VARCHAR (100) NOT NULL
);